spring:
  application:
    name: ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/ecomdb07?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&useSSL=false&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true&serverTimezone=Asia/Dhaka
    username: root
    password: 1234Zaha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082
